config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :services
  resources :service_types

  root to: "welcome#index"
  get '/about' => "welcome#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :service_type
  has_many :histories, :dependent => :delete_all

  def uptime
    histories = self.histories.last(30)
    nb_ping = histories.count
    positive_ping = (histories.select{|history| history.ping == true}).count

    return nb_ping.positive? ? ((positive_ping*100)/nb_ping).to_i : 0
  end

  def ping
    case service_type.name
    when 'Duniter'
      self.ping_duniter
    when 'Cesiumplus'
      self.ping_cesiumplus
    when 'WotWizard'
      self.ping_wotwizard
    else
      self.ping_other
    end
  end

  def get_full_url
    full_url = "#{self.url}"
    slash_index = self.url.index('/')
    slash_index ? full_url.insert(slash_index, ":#{self.port}") : full_url.concat(":#{self.port}")
    full_url.insert(0, self.ssl ? 'https://' : 'http://')
  end

  def ping_duniter
    number = nil
    duration = nil
    full_url = get_full_url
    begin
      requete = RestClient::Request.execute(:method => :get, :url => "#{full_url}/blockchain/current", :timeout => 10, :open_timeout => 10)
      duration = (requete.duration * 1000).to_i
      number = JSON.parse(requete.body)["number"]
    rescue
      puts "Impossible de joindre l'API Duniter pour #{full_url}"
    end

    begin
      requete = RestClient::Request.execute(:method => :get, :url => full_url, :timeout => 10, :open_timeout => 10)
      self.version = JSON.parse(requete.body).first[1]["version"]
      self.save
    rescue
      puts "Impossible de récupérer la version Duniter pour #{self.url}"
    end

    History.create(date: DateTime.now, service_id: self.id, block: number, duration: duration)
  end

  def ping_cesiumplus
    duration = nil
    nb_documents = 0

    begin
      requete = RestClient::Request.execute(:method => :get, :url => "#{self.ssl ? 'https://' : 'http://'}#{self.url}:#{self.port}/node/summary", :timeout => 10, :open_timeout => 10)
      self.version = JSON.parse(requete.body).first[1]["version"]
      #self.status = true
    rescue
      #self.status = false
      puts "Impossible de récupérer la version Cesium+ pour #{self.url}"
    end

    begin
      requete = RestClient::Request.execute(:method => :get, :url => "#{self.ssl ? 'https://' : 'http://'}#{self.url}:#{self.port}/node/stats", :timeout => 10, :open_timeout => 10)
      duration = (requete.duration * 1000).to_i
      nb_documents = requete.split('docs').last.split('count')[1].split(':')[1].split(',').first.to_i
      self.status = nb_documents.positive?
    rescue
      self.status = false
      puts "Impossible de joindre l'API Cesium+ pour #{self.url}"
    end
    self.save

    History.create(date: DateTime.now, service_id: self.id, ping: self.status, nb_documents: nb_documents, duration: duration, error: self.status ? 0 : 1)
  end

  def ping_wotwizard
    begin
      client = SimpleGraphqlClient::Client.new(url: "#{self.ssl ? 'https://' : 'http://'}#{self.url}:#{self.port}")
      version = client.query(gql: %{query {version}}).version
      self.status = !version.empty?
      self.version = version
    rescue
      self.status = false
    end
    self.save

    History.create(date: DateTime.now, service_id: self.id, ping: self.status, error: self.status ? 0 : 1)
  end

  def ping_other
    ping = nil
    begin
      ping = Net::Ping::TCP.new(self.url, self.port).ping?
    rescue
      puts "Erreur de test pour #{self.url}"
      ping = false
    end
    self.status = ping
    self.save

    History.create(date: DateTime.now, service_id: self.id, ping: ping, error: self.status ? 0 : 1)
  end


  def last_block
    return nil unless self.type?('Duniter')

    self.histories.last&.block
  end

  def type?(type_name)
    self.service_type.name == type_name
  end

  def status_classe
    case self.last_error
    when 0
      return 'ok'
    when 1
      return 'ko'
    when 2
      return 'soso'
    else
      return 'nil'
    end
  end

  def check_service(cb=nil)
    cb = self.service_type.current_block if cb.nil?
    history = self.histories.last
    if history
      error = history.define_error(cb)
      self.status = (error==0)
      self.last_error = error
      self.last_nb_documents = history.nb_documents.to_i | history.block.to_i
    end
    self.last_uptime = self.uptime
    self.save
  end

  def nb_documents
    self.histories.last.nb_documents
  end
  
  def error_string
    string = case self.last_error
    when 0
      'status_ok'
    when 1
      'status_down'
    when 2
      'status_late'
    when nil
      nil
    end
    return string
  end
end

app/models/service_type.rb
class ServiceType < ApplicationRecord
    has_many :services, :dependent => :delete_all

    def ping
        self.services.each { |service| service.ping } 
    end

    def current_block
        return nil unless self.name == 'Duniter'

        blocks = []
        self.services.each do |service| 
            block = service.last_block
            blocks << block if block
        end
        return blocks.max.to_i
    end

    def check_services_block
        cb = self.current_block
        self.services.each do |service|
            service.check_service(cb)
        end
    end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ edit update destroy ]

  # GET /services or /services.json
  def index
    @services = Service.all
  end

  # GET /services/1 or /services/1.json
  def show
    @histories = @service.histories.last(30).reverse
  end

  # GET /services/new
  def new
    @service = Service.new
    @service.service_type_id = params[:service_type_id]
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services or /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        @service.ping
        @service.check_service
        format.html { redirect_to @service.service_type, notice: I18n.t('service_created') }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity, alert: I18n.t('service_no_created') }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to service_url(@service), notice: 'service_updated' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity, alert: 'service_no_updated' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1 or /services/1.json
  def destroy
    service_type = @service.service_type_id
    @service.destroy

    respond_to do |format|
      format.html { redirect_to service_type_path(service_type), notice: I18n.t('service_destroyed'), status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:url, :port, :uptime, :ipv4, :ipv6, :admin, :server_funding, :service_type_id, :ssl)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<div class="row justify-content-center">
  <div class="col-lg-6 col-12 text-center">
    <div class="box-column">
      <div class="box-top">
          <i class="bi bi-<%= service.service_type.picto%>" aria-hidden="true"></i><br/>
          <%= I18n.t('creating_instance', type: service.service_type.name) %>
      </div>
      <div class="box-bottom">
        <div class="box-text">
          <div class="container">
            <div class="row">

              <%= form_with(model: service) do |form| %>
                <% if service.errors.any? %>
                  <div style="color: red">
                    <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

                    <ul>
                      <% service.errors.each do |error| %>
                        <li><%= error.full_message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="input-group mb-3">
                  <span class="input-group-text"><i class='bi bi-globe2' title="FQDN"></i></span>
                  <%= form.text_field :url, required: true, class: 'form-control', placeholder: 'FQDN' %>
                  <span class="input-group-text">:</i></span>
                  <%= form.number_field :port, required: true, class: 'form-control', placeholder: I18n.t('port'), min: 0 %>
                </div>

                <div class="input-group mb-3">
                  <div class="input-group-text">
                    <%= form.check_box :ssl, class: "form-check-input mt-0" %>
                  </div>
                  <div class='form-control no-input'>SSL ?</div>
                </div>
                

                <div hidden>
                  <%= form.label :status %>
                  <%= form.check_box :status %>
                </div>

                <div hidden>
                  <%= form.label :uptime %>
                  <%= form.number_field :uptime %>
                </div>

                <div class="input-group mb-3">
                  <span class="input-group-text">IPv4</span>
                  <%= form.text_field :ipv4, required: false, class: 'form-control', placeholder: 'IPv4' %>
                </div>

                <div class="input-group mb-3">
                  <span class="input-group-text">IPv6</span>
                  <%= form.text_field :ipv6, required: false, class: 'form-control', placeholder: 'IPv6' %>
                </div>

                <div class="input-group mb-3">
                  <span class="input-group-text"><i class='bi bi-person' title="<%= I18n.t('admin') %>"></i></i></span>
                  <%= form.text_field :admin, required: true, class: 'form-control', placeholder: I18n.t('admin') %>
                </div>

                <div class="input-group mb-3">
                  <span class="input-group-text"><i class='bi bi-cash' title="<%= I18n.t('server_funding') %>"></i></i></span>
                  <%= form.text_field :server_funding, class: 'form-control', placeholder: I18n.t('server_funding') %>
                </div>

                <div hidden>
                  <%= form.label :service_type_id %>
                  <%= form.text_field :service_type_id %>
                </div>
                <br/>
                <div class='btn-group'>
                  <%= link_to I18n.t('cancel'), service_type_path(service.service_type_id), class: 'btn btn-secondary' %>
                  <%= form.button type: 'submit', class: 'btn btn-primary', onclick: 'loader()' do %>
                      <span id= "spinner" class="spinner-border spinner-border-sm" role="status" aria-hidden="true" style="display: none;"></span>
                      <%= I18n.t('create_instance') %>
                  <% end %> 
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
function loader() {
  document.getElementById('spinner').style.display = 'inline-block';
}
</script>

app/views/services/_service.html.erb
<div class="row justify-content-center">
  <div class="col-xxl-10 col-xl-10 col-lg-10 col-md-10 col-12 text-center">
    <div class="box-column">
      <div class="box-top">
          <i class="bi bi-<%= service.service_type.picto%>" aria-hidden="true"></i><br/>
          <%= service.url%>
      </div>
      <div class="box-bottom">
        <div class="box-text">
          <div class="container">
            <div class="row g-3">

                <div class="col-xl-6 col-lg-12 col-md-12">
                  <div class="input-group mb-3">
                    <span class="input-group-text fix"><%= I18n.t('service_type') %></span>
                    <div class='form-control no-input'><%= service.service_type.name %></div>
                  </div>

                  <div class="input-group mb-3">
                    <span class="input-group-text fix">FQDN</span>
                    <div class='form-control no-input'><%= service.url %></div>
                  </div> 

                  <div class="input-group mb-3">
                    <span class="input-group-text fix"><%= I18n.t('port') %></span>
                    <div class='form-control no-input'><%= service.port %> <%= service.ssl ? 'SSL' : '' %></div>
                  </div>

                  <div class="input-group mb-3">
                    <span class="input-group-text fix"><%= I18n.t('status') %></span>
                    <div class="form-control no-input form-<%= service.status ? 'ok' : 'ko' %>">
                      <%= I18n.t(service.histories.last&.error_string) %>
                    </div>
                  </div>
                </div>

                <div class="col-xl-6 col-lg-12 col-md-12">
                  <div class="input-group mb-3">
                    <span class="input-group-text fix"><%= I18n.t('version') %></span>
                    <div class='form-control no-input'><%= service.version %></div>
                  </div>

                  <% if service.type?('Duniter') %>
                    <div class="input-group mb-3">
                      <span class="input-group-text fix"><%= I18n.t('last_block') %></span>
                      <div class='form-control no-input'><%= service.last_block %></div>
                    </div>
                  <% end %>

                  <% if service.type?('Cesiumplus') %>
                    <div class="input-group mb-3">
                      <span class="input-group-text fix"><%= I18n.t('nb_documents') %></span>
                      <div class='form-control no-input'><%= service.nb_documents %></div>
                    </div>
                  <% end %>

                  <% unless service.ipv4&.empty? %>
                  <div class="input-group mb-3">
                    <span class="input-group-text fix">IPv4</span>
                    <div class='form-control no-input'><%= service.ipv4 %></div>
                  </div>
                  <% end %>

                  <% unless service.ipv6&.empty? %>
                  <div class="input-group mb-3">
                    <span class="input-group-text fix">IPv6</span>
                    <div class='form-control no-input'><%= service.ipv6 %></div>
                  </div>
                  <% end %>

                  <div class="input-group mb-3">
                    <span class="input-group-text fix"><%= I18n.t('admin') %></span>
                    <div class='form-control no-input'><%= service.admin %></div>
                  </div>

                  <div class="input-group mb-3">
                    <span class="input-group-text fix"><%= I18n.t('server_funding') %></span>
                    <div class='form-control no-input funding'><%= service.server_funding %></div>
                  </div>

                </div>
            </div>

            <% if user_signed_in? %>
              <div class='btn-group'>
                <%= link_to I18n.t('edit'), edit_service_path(service), class: 'btn btn-primary' %>
                <%= link_to I18n.t('delete'), service_path(service), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-secondary' %>
              </div>
            <% end %>

            <div class="row mt-5">
              <div class="title-header text-center">
                <h4><%= I18n.t('uptime') %> (%)</h4>
              </div>
              <%= pie_chart({ 'up' => service.uptime, 'down' => (100-service.uptime)}, colors: ["#b1f3b1", "#fdafaf"], legend: "bottom") %>
            </div>
            <div class="row mt-5">
              <div class="title-header text-center">
                <h4><%= I18n.t('latency') %> (ms)</h4>
              </div>
              <%= line_chart History.where("service_id=? AND date>?", service.id, Date.today-30).group_by_day(:date).average(:duration) %>
            </div>
            <div class="row mt-5">
              <div class="title-header text-center">
                <h4><%= I18n.t('history') %> (30 derniers tests)</h4>
              </div>
              <div class="table-responsive">
                <table class="table table-striped-columns">
                  <thead class="thead-dark">
                    <tr>
                      <th><%= I18n.t('date') %></th>
                      <% if service.service_type.name != 'Duniter' and service.service_type.name != 'Cesiumplus' %>
                        <th>Ping?</th>
                      <% end %>
                      <th><%= I18n.t('duration') %> (ms)</th>
                      <% if service.type?('Duniter') %>
                        <th><%= I18n.t('block') %></th>
                      <% end %>
                      <% if service.type?('Cesiumplus') %>
                        <th><%= I18n.t('nb_documents') %></th>
                      <% end %>
                      <th><%= I18n.t('comment') %></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @histories.each do |history| %>
                      <tr>
                        <td><%= history.date.strftime("%d/%m/%Y %H:%M:%S (UTC)") %></td>
                        <% if service.service_type.name != 'Duniter' and service.service_type.name != 'Cesiumplus' %>
                          <td><i class="bi bi-<%= history.ping ? 'check2' : 'x' %>"></i></td>
                        <% end %>
                        <td><%= history.duration %></td>
                        <% if service.type?('Duniter') %>
                          <td><%= history.block %></td>
                        <% end %>
                        <% if service.type?('Cesiumplus') %>
                          <td><%= history.nb_documents %></td>
                        <% end %>
                        <td>
                          <div class="label label-<%= history.ping ? 'ok' : 'ko' %>">
                            <%= I18n.t(history.error_string) %>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>    
      </div>
    </div>
  </div>
</div>

app/views/services/edit.html.erb
<%= render "form", service: @service %>

app/views/services/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Services</h1>

<div id="services">
  <% @services.each do |service| %>
    <%= render service %>
    <p>
      <%= link_to "Show this service", service %>
    </p>
  <% end %>
</div>

<%= link_to "New service", new_service_path %>

app/views/services/new.html.erb
<%= render "form", service: @service %>

app/views/services/show.html.erb
<%= render @service %>   