config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :services
  resources :service_types

  root to: "welcome#index"
  get '/about' => "welcome#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/controllers/service_types_controller.rb
class ServiceTypesController < ApplicationController
  before_action :set_service_type, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new create edit update destroy ]

  # GET /service_types or /service_types.json
  def index
    @service_types = ServiceType.order(:position)
  end

  # GET /service_types/1 or /service_types/1.json
  def show
  end

  # GET /service_types/new
  def new
    @service_type = ServiceType.new
  end

  # GET /service_types/1/edit
  def edit
  end

  # POST /service_types or /service_types.json
  def create
    @service_type = ServiceType.new(service_type_params)

    respond_to do |format|
      if @service_type.save
        format.html { redirect_to service_type_url(@service_type), notice: "Service type was successfully created." }
        format.json { render :show, status: :created, location: @service_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_types/1 or /service_types/1.json
  def update
    respond_to do |format|
      if @service_type.update(service_type_params)
        format.html { redirect_to service_type_url(@service_type), notice: "Service type was successfully updated." }
        format.json { render :show, status: :ok, location: @service_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_types/1 or /service_types/1.json
  def destroy
    @service_type.destroy

    respond_to do |format|
      format.html { redirect_to service_types_url, notice: "Service type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_type
      @service_type = ServiceType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_type_params
      params.require(:service_type).permit(:name, :position, :message, :picto)
    end
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/views/service_types/_form.html.erb
<%= form_with(model: service_type) do |form| %>
  <% if service_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(service_type.errors.count, "error") %> prohibited this service_type from being saved:</h2>

      <ul>
        <% service_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.number_field :position %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_field :message %>
  </div>

  <div>
    <%= form.label :picto, style: "display: block" %>
    <%= form.text_field :picto %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/service_types/_service_type.html.erb
<div class="row justify-content-center">
  <div class="col-xxl-6 col-xl-10 col-lg-10 col-md-10 col-12 text-center">
    <div class="box-column">
      <div class="box-top">
          <i class="bi bi-<%= service_type.picto%>" aria-hidden="true"></i><br/>
          <%= service_type.name%>
      </div>
      <div class="box-bottom">
        <div class="box-text">
          <div class="container">
            <div class="row">
              <div class="row g-3">
                <div class="table-responsive">
                  <table class="table table-striped">
                    <thead class="thead-dark">
                      <tr>
                        <th></th>
                        <th><%= I18n.t('service') %></th>
                        <th><%= I18n.t('version') %></th>
                        <th><%= I18n.t('uptime') %></th>
                        <% if service_type.name == 'Duniter' %>
                          <th><%= I18n.t('block') %></th>
                        <% end %>
                        <% if service_type.name == 'Cesiumplus' %>
                          <th><%= I18n.t('nb_documents') %></th>
                        <% end %>
                        <th><%= I18n.t('status') %></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% service_type.services.order('status DESC').order('last_error DESC').order(:url).each do |service| %>
                        <tr data-link="/services/<%= service.id %>">
                          <td>
                            <%= link_to service, class:'btn btn-secondary btn-sm', title: I18n.t('statistics') do %>
                              <i class="bi bi-graph-up"></i>
                            <% end %>
                            <%= link_to service.get_full_url, class:'btn btn-secondary btn-sm', title: I18n.t('link'), target: '_blank' do %>
                              <i class="bi bi-globe"></i>
                            <% end %>
                          </td>
                          <td><%= link_to service do %>
                            <%= service.url %></td>
                          <% end %>
                          <td><%= service.version %></td>
                          <td><%= service.last_uptime %> %</td>
                          <% if service.type?('Duniter') | service.type?('Cesiumplus') %>
                            <td><%= service.last_nb_documents %></td>
                          <% end %>
                          <td>
                            <div class="label label-<%= service.status_classe %>">
                              <%= I18n.t(service.error_string) %>
                            </div>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <%= link_to new_service_path(service_type_id: service_type.id), class: 'btn btn-primary' do %>
          <i class="bi bi-plus"></i>
          <%= I18n.t('add_instance') %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/service_types/edit.html.erb
<h1>Editing service type</h1>

<%= render "form", service_type: @service_type %>

<br>

<div>
  <%= link_to "Show this service type", @service_type %> |
  <%= link_to "Back to service types", service_types_path %>
</div>

app/views/service_types/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="box">
  <div class="container">
    <div class="row">
      <% @service_types.each do |service_type| %>
        <%= render service_type %>
      <% end %>
    </div>
  </div>
</div>

app/views/service_types/new.html.erb
<h1>New service type</h1>

<%= render "form", service_type: @service_type %>

<br>

<div>
  <%= link_to "Back to service types", service_types_path %>
</div>

app/views/service_types/show.html.erb
<%= render @service_type %>